//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wippien.rc
//
#define IDC_NEXT                        3
#define IDCANCEL2                       3
#define IDC_BACK                        4
#define IDS_SERVICENAME                 100
#define IDR_Wippien                     100
#define IDC_DOWNLOADINGFILE             201
#define IDC_DOWNLOADINGFILE2            202
#define IDC_PROGRESSNUMBER              203
#define IDC_PROGRESS1                   204
#define IDD_ABOUTBOX                    901
#define IDB_SETUP                       1001
#define IDC_LIST1                       1002
#define IDC_MSGWIN_USERS                1002
#define IDC_CHATROOM_ROOMLIST           1002
#define IDC_LISTREGISTEREDGATEWAYS      1003
#define IDC_INTERFACELIST               1004
#define IDC_SKINLIST                    1005
#define IDC_LIST112                     1006
#define IDC_STATUS                      1007
#define IDD_SETTINGS_JID                1008
#define IDC_BUTTON1                     1009
#define IDC_CHATROOM_JOIN               1009
#define IDC_FIREWALLRULE_ADD            1009
#define IDC_ADDNEW                      1010
#define IDC_SETTINGS_USER4_RESETALL     1011
#define IDC_BUTTON3                     1011
#define IDC_FIREWALLRULE_REMOVE         1011
#define IDC_UPDATE_CHECKNOW             1012
#define IDB_PLAY                        1013
#define IDC_BUTTON2                     1014
#define IDC_LBL_TITLE                   1015
#define IDC_STATIC_NEXT                 1017
#define IDC_REMOVEGROUP                 1018
#define IDC_LBL_WELCOME                 1019
#define IDB_WATERMARK                   1020
#define IDC_EDIT_JID                    1021
#define IDC_LABEL_JID                   1023
#define IDC_LABEL_JID1                  1024
#define IDC_LABEL_JID2                  1025
#define IDD_SETTINGS_RSA                1026
#define IDB_BUTTON_JID1                 1027
#define IDD_NEEDPASS                    1028
#define IDC_EDIT2_JID                   1029
#define IDD_SETTINGS_PICTURE            1030
#define IDD_SETTINGS_ETHERNET           1031
#define IDC_TEST_JID                    1032
#define IDC_JABBER_CONN_STATUS          1033
#define IDC_LABEL_RSA1                  1034
#define IDC_EDIT_JID3                   1035
#define IDB_GENERATE                    1036
#define IDC_EDIT_JID4                   1037
#define IDB_BROWSE                      1038
#define IDB_LOAD                        1039
#define IDC_LABEL_ETHERNET1             1040
#define IDB_BROWSE2                     1041
#define IDC_LABEL_ETHERNET2             1042
#define IDB_BROWSE4                     1042
#define IDB_BROWSE3                     1043
#define IDC_IP_ETHERNET                 1044
#define IDC_CHECK_ETHERNET              1045
#define IDR_SOUNDON                     1046
#define IDC_MEDIATOR                    1048
#define IDC_IPOBTAINURL                 1048
#define IDR_SOUNDOFF                    1049
#define IDC_LINKMEDIATOR_HOSTNAME       1049
#define IDC_CHECK_ETHERNETSHOWMEDIATOR  1050
#define IDC_LINKMEDIATOR_PORT           1050
#define IDC_CHECK_SHOWMEDIATOR          1051
#define IDR_SOUNDMSGIN                  1052
#define IDC_CHECK_ETHERNETMEDIATOR      1053
#define IDC_CHECK_ALLOWANYMEDIATOR      1054
#define IDR_SOUNDMSGOUT                 1055
#define IDC_DETECT                      1056
#define IDD_MAINDLG                     1057
#define IDR_PROGRAMICON                 1058
#define IDB_BELL                        1060
#define IDB_GROUPOPENED                 1061
#define IDB_GROUPCLOSED                 1062
#define IDB_DRAGDROP                    1063
#define IDD_MSGDLG                      1064
#define IDR_USERLISTPOPUP               1065
#define IDD_INSERTHYPERLINKDLG          1066
#define IDB_BOLD                        1067
#define IDB_ITALIC                      1068
#define IDB_UNDERLINE                   1069
#define IDB_FONTSIZEUP                  1070
#define IDB_FONTSIZENORMAL              1071
#define IDB_FONTSIZEDOWN                1072
#define IDB_HYPERLINK                   1073
#define IDB_FONTFORECOLOR               1074
#define IDR_SETUPPOPUP                  1075
#define IDB_FONTBACKCOLOR               1076
#define IDD_SETTINGS_ACCOUNTS           1077
#define IDB_SERVICE_ICQ                 1078
#define IDB_EMOTICONS                   1079
#define IDB_SERVICE_YAHOO               1080
#define IDB_SERVICE_AIM                 1081
#define IDB_SERVICE_MSN                 1082
#define IDB_SERVICE_GOOGLE              1083
#define IDD_AUTHORIZATIONDIALOG         1084
#define IDD_DIALOG1                     1085
#define IDD_SETTINGS_CONTACTS_ADDREMOVE 1086
#define IDD_RENAMECONTACT               1087
#define IDD_SETTINGS_CONTACTS           1088
#define IDD_SETTINGS                    1089
#define IDR_SPLASH                      1090
#define IDB_AUTHWAIT                    1091
#define IDR_AWAYPOPUP                   1092
#define IDD_SETTINGS_LOG                1093
#define IDD_SETTINGS_MEDIATOR           1094
#define IDR_SOUNDNONO                   1095
#define IDD_SETTINGS_MSGWIN             1096
#define IDD_SETTINGS_USER_1             1097
#define IDD_SETTINGS_USER_2             1098
#define IDD_SETTINGS_USER_3             1099
#define IDD_SETTINGS_USER_4             1100
#define IDD_SETTINGS_SKINS              1101
#define IDR_SETTINGSICON                1102
#define IDR_MSGWINICON                  1103
#define IDD_SETTINGS_AUTOAWAY           1104
#define IDD_SETTINGS_SYSTEM             1105
#define IDR_PROGRESSWINICON             1107
#define IDD_DOWNLOADSKIN                1108
#define IDD_PROGRESS                    1109
#define IDD_BALLOONTIP                  1110
#define IDB_BITMAP1                     1111
#define IDR_PICTUREPOPUP                1112
#define IDD_SETTINGS_VOICECHAT          1113
#define IDD_SETTINGS_SYSTEM_UPDATE      1114
#define IDD_SETTINGS_MTU                1115
#define IDD_SETTINGS_SOUNDS             1116
#define IDD_SETTINGS_CONTACTS_HIDE      1117
#define IDD_HIDECONTACT                 1118
#define IDD_SETTINGS_APPEARANCE         1119
#define IDC_SERVICE_DESCRIPTION         1120
#define IDD_SETTINGS_CONTACTS_SORT      1121
#define IDC_STATIC_USERNAME             1122
#define IDC_STATIC_PASSWORD             1123
#define IDC_AUTHSTATICTEXT              1124
#define IDC_GROUPLIST                   1125
#define IDC_AUTHSTATICTEXT2             1126
#define IDC_ADDNEWGROUP                 1127
#define IDC_CONTACTID                   1128
#define IDC_CONTACTTYPELIST             1129
#define IDC_VISIBLENAME                 1130
#define IDC_ADDNEWCONTACT               1131
#define IDC_CONTACTVISIBLE              1132
#define IDC_TREE1                       1133
#define IDC_TEXT1                       1134
#define IDC_TEXT2                       1135
#define IDC_BORDER1                     1136
#define IDC_BITMAP                      1137
#define IDC_MYSTATUS                    1138
#define IDC_MYCONTACTS                  1139
#define IDC_TREEBITMAP                  1140
#define IDC_MYAUTHDLG                   1141
#define IDC_MOREWAITING                 1142
#define IDC_CHATROOMS                   1142
#define IDC_SMALLMUTE                   1143
#define IDC_APPLYTOALL                  1144
#define IDC_DETAILS                     1145
#define IDC_CONTACTJID                  1146
#define IDC_LOG_JABBER                  1147
#define IDC_BLOCKUSER                   1147
#define IDC_LOG_SOCKET                  1148
#define IDC_VISIBLEDATA                 1149
#define IDC_UDP_PORT                    1150
#define IDC_ISTYPING                    1151
#define IDC_TIMESTAMP_MESSAGES          1152
#define IDC_SHOW_MESSAGE_HISTORY        1153
#define IDC_LOG_FUNCTION                1154
#define IDC_WIPPIEN_VERSION             1155
#define IDC_WODJABBER_VERSION           1156
#define IDC_PERSONAL_JID                1157
#define IDC_EDIT1                       1158
#define IDC_IPADDRESS                   1158
#define IDC_CHATROOM_NICKNAME           1158
#define IDC_SETTINGS_USER3_ADDRESS      1159
#define IDC_IPADDRESSNETMASK            1159
#define IDC_NETMASK_ETHERNET            1159
#define IDC_AUTOAWAYMINUTES             1160
#define IDC_NAME                        1161
#define IDC_PASSWORDPROTECTPASSWORD     1162
#define IDC_USEFIXEDMTUNUM              1163
#define IDC_SOUND                       1164
#define IDC_WODAPPUPDATE_VERSION        1165
#define IDC_EDIT2                       1166
#define IDC_WODVPN_VERSION              1166
#define IDC_CHATROOM_ROOMNAME           1166
#define IDC_SETTINGS_USER3_ADDRESSEXT   1167
#define IDC_CHATROOM_ROOMPASS           1167
#define IDC_EXTENDEDAWAYMINUTES         1168
#define IDC_EMAIL                       1169
#define IDC_FUNCTIONDELETEMB            1170
#define IDC_SETTINGSFOLDER              1171
#define IDC_EDIT3                       1172
#define IDC_SETTINGS_USER3_CITY         1173
#define IDC_AUTODISCONNECTMINUTES       1174
#define IDC_EDIT4                       1175
#define IDC_SETTINGS_USER3_STATE        1176
#define IDC_AUTOAWAYMESSAGE             1177
#define IDC_EDIT5                       1178
#define IDC_SETTINGS_USER3_ZIP          1179
#define IDC_EXTENDEDAWAYMESSAGE         1180
#define IDC_EDIT6                       1181
#define IDC_SETTINGS_USER3_COUNTRY      1182
#define IDC_EDIT10                      1183
#define IDC_SETTINGS_USER3_COMPANY      1184
#define IDC_DATETIMEPICKER1             1185
#define IDC_EDIT11                      1186
#define IDC_SETTINGS_USER2_BDAY         1187
#define IDC_SETTINGS_USER3_DEPARTMENT   1188
#define IDC_EDIT7                       1189
#define IDC_SETTINGS_USER3_PHONE        1190
#define IDC_EDIT8                       1191
#define IDC_SETTINGS_USER3_FAX          1192
#define IDC_EDIT9                       1193
#define IDC_SETTINGS_USER3_TITLE        1194
#define IDC_SETTINGS_USER1_NICKNAME     1195
#define IDC_SETTINGS_USER1_FIRSTNAME    1196
#define IDC_SETTINGS_USER1_LASTNAME     1197
#define IDC_SETTINGS_USER1_EMAIL        1198
#define IDC_SETTINGS_USER1_URL          1199
#define IDC_SETTINGS_USER1_DESCRIPTION  1200
#define IDC_SETTINGS_USER2_ADDRESS      1201
#define IDC_SETTINGS_USER2_ADDRESSEXT   1202
#define IDC_SETTINGS_USER2_CITY         1203
#define IDC_SETTINGS_USER2_STATE        1204
#define IDC_SETTINGS_USER2_ZIP          1205
#define IDC_SETTINGS_USER2_COUNTRY      1206
#define IDC_SETTINGS_USER2_PHONE        1207
#define IDC_SETTINGS_USER2_FAX          1208
#define IDC_STATIC_BIRTHDAY             1209
#define ID_EXIT                         1210
#define IDC_MOREREQUESTSWAITING         1211
#define IDC_SETBACKONACTIVITY           1212
#define IDC_SHOWINTASKBAR               1213
#define IDC_ABOUT_PICTURE               1214
#define IDC_ALIGNTOBORDER               1215
#define IDC_ALWAYSONTOP                 1216
#define IDC_LICENSED_TO                 1217
#define IDC_CHECKUPDATE                 1218
#define IDB_SKINPREVIEW                 1219
#define IDC_SNAPTOBORDER                1220
#define IDC_CHECKUPDATE_TIMED           1221
#define IDB_APPLY                       1222
#define IDC_ALWAYSONTOP2                1223
#define IDC_CHECKUPDATE_CONNECT         1224
#define IDC_COMBO1                      1225
#define IDC_CHATROOM_GATEWAYLIST        1225
#define IDC_CONTACTLIST                 1226
#define IDC_CHATROOM_GATEWAY2           1226
#define IDB_MORESKINS                   1227
#define IDC_VOICE_PLAYBACKDEVICE        1228
#define IDC_STATICIP                    1229
#define IDC_VOICE_RECORDINGDEVICE       1230
#define IDC_EXPLORER1                   1231
#define ID_CANCEL                       1232
#define IDC_EXPLORERGETGIF              1233
#define IDC_EXPLORERGETSWF              1234
#define IDC_RADIO1_JID                  1235
#define IDC_RADIO2_JID                  1236
#define IDC_PROGCTRL1                   1237
#define ID_WIPUPD                       1240
#define IDC_BALLOONTIPSTATIC            1244
#define IDC_BALLOONTIPTEXT              1245
#define IDC_BALLOONTIPMESSAGE           1246
#define IDC_ENABLEVOICECHAT             1247
#define IDC_PASSWORDPROTECTSETTINGS     1248
#define IDC_PASSWORDPROTECTEVERYTHING   1249
#define IDC_ENTERPASSPHRASE             1250
#define IDC_CONTACTS_DELETEONSTARTUP    1251
#define IDC_CONTACTS_AUTOASSIGNIP       1252
#define IDC_CONTACTS_DELETEONCONNECT    1253
#define IDC_CHECKUPDATESILENTLY         1254
#define IDC_AUTOCONNECTONTRAFFIC        1255
#define IDC_SHOWUPDATERMESSAGES         1255
#define IDC_CHECKUPDATE_TIMEDNUM        1256
#define IDC_AUTOCONNECTONSTARTUP        1257
#define IDC_RELEASEIPONVPNDISCONNECT    1258
#define IDC_USEFIXEDMTU                 1259
#define IDC_AUTODETECTMTU               1260
#define IDC_AUTODETECTMTUNUM            1261
#define IDC_SORTBYIPTOP                 1262
#define IDC_SORTBYIPBOTTOM              1263
#define IDC_SOUNDEVENTS                 1264
#define IDC_SORTNONE                    1265
#define IDC_CONFIRMEXIT                 1266
#define IDC_UNBLOCKCONTACT              1267
#define IDC_USEPOWEROPTIONS             1267
#define IDC_BLOCKNEWCONTACT             1268
#define IDC_HIDDENCONTACTS              1269
#define IDC_SHOWCONTACTPICTURE          1270
#define IDC_SHOWCONTACTNAME             1271
#define IDC_SHOWCONTACTIP               1272
#define IDC_SHOWCONTACTSTATUS           1273
#define IDC_SHOWPICTURE                 1274
#define IDC_SHOWNAME                    1275
#define IDC_SHOWIP                      1276
#define IDC_SHOWSTATUS                  1277
#define IDC_SHOWCONTACTLASTONLINE       1278
#define IDC_SORTBYNAME                  1279
#define IDC_SHOWCONTACTACTIVITYMONITOR  1279
#define IDC_SORTBYJID                   1280
#define IDC_CONTACTS_AUTH0              1281
#define IDC_CONTACTS_AUTH1              1282
#define IDC_CONTACTS_AUTH2              1283
#define IDC_LIST                        1284
#define IDC_CHOOSEICON                  1285
#define IDB_SEND                        1286
#define IDC_EDITOR                      1287
#define IDC_BOLD                        1288
#define IDC_ITALIC                      1289
#define IDC_UNDERLINE                   1290
#define IDC_HYPERLINK                   1291
#define IDC_FONTSIZEDOWN                1292
#define IDC_EDITHYPERLINK               1293
#define IDC_KEY                         1294
#define IDC_FONTSIZENORMAL              1295
#define IDC_EDITDESCRIPTION             1296
#define IDC_LOADKEYFILE                 1297
#define IDC_FONTSIZEUP                  1298
#define IDC_EMOTICONS                   1299
#define IDC_PASSWORD                    1300
#define IDC_PERSON                      1301
#define IDC_TREELIST                    1302
#define IDC_RENAMEEDIT                  1303
#define IDC_FONTFORECOLOR               1304
#define IDC_FONTBACKCOLOR               1305
#define IDC_ADDNEWACCOUNT               1307
#define IDC_OPENNEWACCOUNT              1308
#define IDC_NEW_STATIC                  1309
#define IDC_EDIT_SCREENNAME             1310
#define IDC_EDIT_PASSWORD               1311
#define IDC_REGISTERNEWACCOUNT          1312
#define IDC_AUTOCONNECT                 1313
#define IDC_REGISTERNEWACCOUNT2         1314
#define IDC_ACCOUNT_REGISTER            1315
#define IDC_CANCELNEW                   1316
#define IDC_REMOVEACCOUNT               1317
#define IDC_ORDERNOW                    1318
#define ID_PNG1_CHAT                    1320
#define ID_PNG1_SENDFILE                1321
#define ID_PNG1_SENDEMAIL               1322
#define ID_PNG1_BLOCK                   1323
#define ID_PNG1_RENAME                  1324
#define ID_PNG1_DELETE                  1325
#define ID_PNG1_DETAILS                 1326
#define ID_PNG1_COPYADDRESS             1327
#define ID_PNG1_MUTEONOFF               1328
#define ID_PNG1_MUTEON                  1329
#define ID_PNG1_MUTEOFF                 1330
#define ID_PNG2_MUTEON                  1331
#define ID_PNG2_MUTEOFF                 1332
#define ID_PNG2_SENDFILE                1333
#define ID_PNG2_DETAILS                 1334
#define ID_PNG_SKINBASE                 1335
#define ID_PNG_AVATARBASE               1336
#define ID_PNG_CLEARHISTORY             1337
#define ID_PNG1_CLEARHISTORY            1338
#define IDB_HUMAN1                      1339
#define IDB_HUMAN2                      1340
#define IDB_HUMAN3                      1341
#define IDB_HUMAN4                      1342
#define IDB_HUMAN5                      1343
#define IDB_HUMAN6                      1344
#define IDB_HUMAN7                      1345
#define IDB_HUMAN8                      1346
#define IDB_HUMAN9                      1347
#define IDB_HUMAN10                     1348
#define IDB_HUMAN11                     1349
#define IDB_HUMAN12                     1350
#define IDB_HUMAN13                     1351
#define IDB_HUMAN14                     1352
#define IDB_HUMAN15                     1353
#define IDB_HUMAN16                     1354
#define IDB_HUMAN17                     1355
#define IDB_HUMAN18                     1356
#define IDB_HUMAN19                     1357
#define IDB_HUMAN20                     1358
#define IDB_HUMAN21                     1359
#define IDB_HUMAN22                     1360
#define IDB_HUMAN23                     1361
#define IDB_HUMAN24                     1362
#define IDB_HUMAN25                     1363
#define IDB_HUMAN26                     1364
#define IDB_HUMAN27                     1365
#define IDB_HUMAN28                     1366
#define IDB_HUMAN29                     1367
#define IDB_HUMAN30                     1368
#define IDB_HUMAN31                     1369
#define IDB_HUMAN32                     1370
#define IDB_HUMAN33                     1371
#define IDB_HUMAN34                     1372
#define IDB_HUMAN35                     1373
#define IDB_HUMAN36                     1374
#define IDB_HUMAN37                     1375
#define IDD_APPUPDPROGRESS              1376
#define ID_PNG1_CHATROOMS               1380
#define IDD_CHATROOMS_DLG               1382
#define IDD_SETTINGS_CHATROOMS          1382
#define IDI_ICON_YES                    1383
#define IDI_ICON_NO                     1384
#define IDD_SETTINGS_NETWORK_FIREWALL   1385
#define IDC_IPADDRESSIGNORE             1477
#define IDC_IPADDRESSBYIPMEDIATOR       1478
#define IDC_IPADDRESSSTATIC             1479
#define IDC_ETHERNET_IP                 1480
#define IDC_USESSLWRAPPER               1482
#define IDC_LOG_VPNSOCKET               1483
#define IDI_STATUS_ONLINE               1484
#define IDI_STATUS_OFFLINE              1485
#define IDI_STATUS_AWAY                 1486
#define IDI_STATUS_XA                   1487
#define IDI_STATUS_DND                  1488
#define IDI_STATUS_INVISIBLE            1489
#define IDI_STATUS_FFC                  1490
#define IDC_CHATROOM_BLOCKUSERSATSTARTUP 1491
#define IDC_MEDIATORLIST                1492
#define IDC_ALLOWTRAFFIC                1494
#define IDC_BLOCKTRAFFIC                1495
#define IDC_TCP                         1496
#define IDC_UDP                         1497
#define IDC_PING                        1498
#define IDC_ICMP                        1498
#define IDC_RULES                       1499
#define IDC_STATICBLOCK                 1500
#define ID_POPUP1_CHAT                  32770
#define ID_POPUP1_SENDFILE              32771
#define ID_POPUP1_SENDEMAIL             32772
#define ID_POPUP1_BLOCK                 32773
#define ID_POPUP1_RENAME                32774
#define ID_POPUP1_DELETE                32775
#define ID_POPUP1_DETAILS               32776
#define ID_POPUP1_COPYADDRESS           32777
#define ID_POPUP2_IDENTITIES            32778
#define ID_POPUP2_NEWCONTACT            32779
#define ID_POPUP3                       32782
#define ID_POPUP3_ONLINE                32784
#define ID_POPUP3_AWAY                  32785
#define ID_POPUP3_CHAT                  32786
#define ID_POPUP3_DONOTDISTURB          32787
#define ID_POPUP3_EXTENDEDAWAY          32788
#define ID_POPUP3_OFFLINE               32790
#define ID_POPUP3_INVISIBLE             32791
#define ID_POPUP4_CHANGEPICTURE         32792
#define ID_POPUP4_YOUR_DETAILS          32793
#define ID_POPUP1_VOICECHAT             32794
#define ID_POPUP_LISTCHATROOMS          32795
#define ID_POPUP_JOINACHATROOM          32796
#define ID_APP_ABOUT                    0xE140

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1386
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1501
#define _APS_NEXT_SYMED_VALUE           1576
#endif
#endif
